apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init-user.sh: |
    #!/bin/bash
    mongo namegen --eval "
      db.createUser({
        user: '$APP_DB_USER',
        pwd: '$APP_DB_PASSWORD',
        roles: [
          { role: 'readWrite', db: 'namegen' }
        ]
      })
    "
