apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  username: YOUR_MONGODB_USERNAME
  password: YOUR_MONGODB_PASSWORD
  mongodb-url: mongodb://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@mongodb/namegen
